#To be tested 11/10/2018 LCPT
SET(CPACK_GENERATOR "DEB")
INCLUDE(InstallRequiredSystemLibraries)

SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "xc_basic")
SET(CPACK_PACKAGE_VENDOR "XC")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${xc_basic_DIR}/readme.txt")
SET(CPACK_RESOURCE_FILE_LICENSE "${xc_basic_DIR}/license.txt")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "12")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")

SET(CPACK_DEBIAN_PACKAGE_NAME "xc_basic")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libstdc++6 (>=4.3), libgcc1 (>=1:4.3), libc6 (>=2.7), libvtk5 (>=5.0)")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Luis C. Pérez Tato") #required
SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "XC Basic Library.")
SET(CPACK_DEBIAN_PACKAGE_SECTION "contrib/science")
 
INCLUDE(CPack)
